### PR TITLE
new, add population bounds

### PR DESCRIPTION
**Pull request by GiggleLiu**
Add a clip bounds for populations.

#59

### CODE REVIEW

**Comment by wildart** [comment]
As I added NLSolversBase dependency, now the [`ConstraintBounds`](https://github.com/JuliaNLSolvers/NLSolversBase.jl/blob/master/src/objective_types/constraints.jl) is available. Why don't yo use them?

I think you need to put  constrains as parameter to `optimize` function,  not in optimization options.

**Comment by wildart** [comment]
I added constrains parameter to the optimization interface. You can use `bounds` field of `constrains` object to check available [ConstraintBounds](https://github.com/JuliaNLSolvers/NLSolversBase.jl/blob/1e5d1750b7c3566065160e89a6066c82deaf3947/src/objective_types/constraints.jl).

Moreover, I do not think that every offspring need to be checked for constraint violations, only the fittest individual at the end of the state update, so next offspring will be constrained.

**Comment by GiggleLiu** [comment]
> I added constrains parameter to the optimization interface. You can use bounds field of constrains object to check available ConstraintBounds.

Yeah, I noticed. However, it is more likely designed for lagrange multiplier. I don't know how to "clip" parameters according to the bounds. Do you have any clue?

> Moreover, I do not think that every offspring need to be checked for constraint violations, only the fittest individual at the end of the state update, so next offspring will be constrained.

I am running an experiment, where the time is a parameter. Every individual should keep the time possitive. Make sense?

**Comment by wildart** [comment]
I just pushed https://github.com/wildart/Evolutionary.jl/commit/ce57352e5ccac6c7550e1f68d3d05a0378187698. Take a look.

**Comment by wildart** [comment]
Implemented in v0.7.0

**Comment by GiggleLiu** [comment]
Sorry for the late reply.
I just read your code, the functionaliy and tests looks good. From the user pespective, I have two minor comments:

* overloading `value` function looks confusing to me. It has been used in obtaining the objective function.
* there has been manypoistional arguments in optimize, making the constraints the second argument is not easy to memorize.

**Comment by wildart** [comment]
> overloading `value` function looks confusing to me. It has been used in obtaining the objective function.

Indeed, and now it's a value of the obj. function w.r.t. constraints. Do you have something else on your mind?

> there has been many poistional arguments in optimize, making the constraints the second argument is not easy to memorize.

I see it as follows. 
- First, an objective function,
- Next if present any constraints in form of lower/upper bounds or a constraints object
- an initial individual,
- a method
- options

I'll try to put it in the tutorial part of the docs.

**Comment by GiggleLiu** [comment]
`penalty(constraints, x)` is general purposed. IIUC, transfinite constraint is a special case of box constraint, so why not using `clip!` (it is a name widely used in gradient based optimizers) directly?
Or you may want to use some explicit names like `apply_constraint`.

About the second point, I think making it a keyword argument would be very explicit.
BTW: What is `options` for, they can be keyword arguments too.

**Comment by GiggleLiu** [comment]
FYI: scipy uses both `constraints` and `bounds`.
https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html

**Comment by wildart** [comment]
> FYI: scipy uses both `constraints` and `bounds`.

I went along with `Optim.jl` interface for `optimize` call with constraints/bounds.

https://github.com/JuliaNLSolvers/Optim.jl/blob/570debf088869bce270ec5c9a531fff0802f9da0/docs/src/examples/ipnewton_basics.jl#L54
or
https://github.com/JuliaNLSolvers/Optim.jl/blob/80bbd32d2198b273cd6a581fdc4c82ff3a6cafeb/src/multivariate/solvers/constrained/fminbox.jl#L156-L166

I do not find it particularly bad. Usually, your `optimize` call would have 3-4 parameters which is not cumbersome. If you solve a problem with constraints, they need to be explicitly stated. In form of keyword arguments, they would look like an optional features.

> IIUC, transfinite constraint is a special case of box constraint, so why not using clip! (it is a name widely used in gradient based optimizers) directly?

Transfinite constraint is sort of silly practice. I'm going to remove it.

**Comment by wildart** [comment]
What do you think of this? https://github.com/wildart/Evolutionary.jl/blob/43098c3e6780fcbb978f935134875c1f4771ac9d/src/api/constraints.jl#L3-L29

**Pull request closed without merging**
